#!/bin/bash
set -Eeuo pipefail

: "${BASHBREW_CACHE:=$HOME/.cache/bashbrew}"
export BASHBREW_CACHE

refsList="$(
	bashbrew list --uniq "$@" \
		| sort -u \
		| sed \
			-e 's!:!/!' \
			-e 's!^!refs/tags/'"${BASHBREW_ARCH:+$BASHBREW_ARCH/}"'!' \
			-e 's!$!:!'
)"
IFS=$'\n'
refs=( $refsList )
unset IFS

git -C "$BASHBREW_CACHE/git" fetch --no-tags https://github.com/tianon/bad-ideas.git "${refs[@]}"
