#!/usr/bin/env bash
set -Eeuo pipefail

args=(
	--interactive --rm
	--network host
	--name speedtest
)

if [ -t 0 ] && [ -t 1 ]; then
	args+=( --tty )
fi

exec docker run "${args[@]}" tianon/speedtest "$@"
