#!/usr/bin/env bash
set -Eeuo pipefail

uid="$(id -u)"
gid="$(id -g)"
hostname="$(hostname --short)"

self="$(basename "$0")"
self="${self%-docker}"
home="$HOME/homes/$self"
args=(
	--rm
	--security-opt no-new-privileges
)
image="tianon/$self"
case "$self" in
	steam)
		;;

	lutris)
		args+=(
			# Lutris uses $USER for Wine home directory detection
			--env USER="$uid"
			# https://github.com/lutris/lutris/blob/4315ba26f55dc208105b8abebf49d9ec28a67a1b/lutris/util/wine/prefix.py#L97
		)
		;;

	zoom)
		for device in /dev/video[0-9]*; do
			if [ -c "$device" ]; then
				args+=( --device "$device" )
			fi
		done
		;;

	slack)
		# TODO figure out how to get over this properly instead D: (probably similar to what Edge needs)
		args+=(
			--cap-add SYS_ADMIN
			--security-opt no-new-privileges=false
		)
		;;

	*)
		echo >&2 "error: unknown Docker image: $self"
		exit 1
		;;
esac

args+=(
	--name "$self"
	--init --rm
	--hostname "$hostname-docker"
)

mkdir -p "$home"
home="$(cd "$home" && pwd -P)"

args+=(
	--user "$uid:$gid"

	--mount type=bind,src="$home",dst="/$self-home"
	--env HOME="/$self-home"
	--workdir "/$self-home"

	--mount type=bind,src=/tmp/.X11-unix,dst=/tmp/.X11-unix,ro
	--env DISPLAY
	--device /dev/dri # OpenGL
	--ipc host # DevShm errors

	--mount type=bind,src=/etc/localtime,dst=/etc/localtime,ro
	--mount type=bind,src=/etc/machine-id,dst=/etc/machine-id,ro
	--mount type=bind,src=/var/run/dbus,dst=/var/run/dbus,ro

	# TODO figure out why Proton requires this, and give it a more specific profile instead
	--security-opt seccomp:unconfined
)
for addGid in $(id -G); do
	if [ "$addGid" != "$gid" ]; then
		args+=( --group-add "$addGid" )
	fi
done

buildNeedsSanity=1
_build() {
	local suffix="$1"; shift
	local newImage="$image"
	case "$image" in
		*:*) newImage+="-$suffix" ;;
		*)   newImage+=":$suffix" ;;
	esac
	local sanity=$'USER root\nRUN grep -qF ID=ubuntu /etc/os-release\n'
	if [ -n "$buildNeedsSanity" ]; then
		buildNeedsSanity=
	else
		sanity=
	fi
	local steps; steps="$(cat)"
	docker build --tag "$newImage" - <<-EODF
		FROM $image
		$sanity
		$steps
	EODF
	image="$newImage"
}

# NVIDIA...
if glxinfo="$(glxinfo -B 2>/dev/null)" && grep -qF 'OpenGL vendor string: NVIDIA Corporation' <<<"$glxinfo"; then
	# time to get creative...?
	if nvidiaVersion="$(sed -rne '/^OpenGL version string:.*NVIDIA ([0-9]{3,}[.][0-9]+).*/s//\1/p' <<<"$glxinfo")" && [ -n "$nvidiaVersion" ]; then
		nvidiaMajor="${nvidiaVersion%%.*}"
		_build "nvidia-$nvidiaVersion" <<-EODF
			RUN set -eux; \
				apt-get update; \
				apt-get install -y --no-install-recommends \
					pkg-config \
				; \
				rm -rf /var/lib/apt/lists/*
			RUN set -eux; \
				wget -O nvidia.run 'http://us.download.nvidia.com/XFree86/Linux-x86_64/$nvidiaVersion/NVIDIA-Linux-x86_64-$nvidiaVersion.run' --progress=dot:giga; \
				chmod +x nvidia.run; \
				./nvidia.run --advanced-options; \
				./nvidia.run \
					--no-questions \
					--ui=none \
					--no-nvidia-modprobe \
					--no-rpms \
					--no-backup \
					--no-kernel-module \
					--no-nouveau-check \
					--no-check-for-alternate-installs \
				; \
				rm nvidia.run
		EODF
		for device in /dev/nvidia*; do
			if [ -e "$device" ]; then
				args+=( --device "$device" )
			fi
		done
	else
		echo >&2 'error: NVIDIA detected, but version number not found!'
		echo >&2
		echo >&2 "$glxinfo"
		echo >&2
		exit 1
	fi
fi

if [ -d /dev/input ]; then
	args+=( --mount type=bind,src=/dev/input,dst=/dev/input,ro )

	majors="$(find /dev/input -type c -exec stat --format='%t' '{}' + | sort -u)"
	for major in $majors; do
		majorDec="$(( 16#$major ))"
		args+=( --device-cgroup-rule "c $majorDec:* rmw" )
	done
fi
if [ -e /dev/uinput ]; then
	args+=( --device /dev/uinput )
fi
if [ -d /run/udev ]; then
	args+=( --mount type=bind,src=/run/udev,dst=/run/udev,ro )
fi
for device in /dev/hidraw*; do
	[ -c "$device" ] || continue
	args+=( --device "$device" )
done

if [ -d "${XDG_RUNTIME_DIR:-}" ] && [ -S "$XDG_RUNTIME_DIR/pulse/native" ]; then
	args+=(
		--mount type=bind,src="$XDG_RUNTIME_DIR/pulse",dst=/pulse,ro
		--env PULSE_SERVER='unix:/pulse/native'
	)
fi

args+=( --interactive )
if [ -t 0 ] && [ -t 1 ]; then
	args+=( --tty )
fi

case "${DEBUGGER:-}" in
	'') ;;
	strace | gdb)
		_build "debug-$DEBUGGER" <<-EODF
			RUN set -eux; \
				apt-get update; \
				apt-get install -y --no-install-recommends $DEBUGGER; \
				rm -rf /var/lib/apt/lists/*
		EODF
		args+=(
			--env DEBUGGER
			--cap-add SYS_PTRACE
			--security-opt seccomp:unconfined
			--security-opt apparmor:unconfined
		)
		;;
esac

set -x
exec docker run "${args[@]}" "$image" "$@"
